kind: BuildConfig
metadata:
    name: certbot-buildconfig
    description: Build configuration for the certbot image
spec:
    output:
        to:
            kind: ImageStreamTag
            name: certbot-imagestream:latest
    source:
        git:
            ref: ""
            uri: https://github.com/ukcloud-rubeon/openshift-letsencrypt.git
        type: Git
    strategy:
        type: Source
        sourceStrategy:
            from:
                kind: DockerImage
                name: rhscl/python-27-rhel7
    triggers:
        - type: ImageChange
        - type: ConfigChange
                